/*
===============================================================
 #CUSTOM JavaScript
- Please do not edit this file. This file is generated from admin area.
- Every changes here will be overwritten by theme
===============================================================*/
    /* theme_options_custom 
=========================*/
    jQuery('.aux-modern-form').each( function(){
        jQuery(this).auxModernForm();
    });
